### ISSUE TITLE
在导入sdk到自己的项目里后，登录dialog弹出失败

### ISSUE THREAD

**Issue by Leolhy** [DJI-Mobile-SDK-Tutorials/Android-UXSDKDemo#13]
异常信息，java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
                                                                     at dji.internal.useraccount.a.a.b(Unknown Source:39)
                                                                     at dji.internal.useraccount.a.a.onCreate(Unknown Source:3)
                                                                     at android.app.Dialog.dispatchOnCreate(Dialog.java:528)
                                                                     at android.app.Dialog.show(Dialog.java:389)
                                                                     at dji.internal.useraccount.a$4.run(Unknown Source:15)
                                                                     at android.os.Handler.handleCallback(Handler.java:808)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:101)
                                                                     at android.os.Looper.loop(Looper.java:166)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:7523)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
由于看不见源码，无法定位异常原因。

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/27684'>Zendesk ticket #27684</a>:<br><br>尊敬的用户，

您好！感谢您联系DJI 大疆创新。
为了快速收集问题细节，麻烦您详细填写如下表格。
https://formcrafts.com/a/dji-developer-feedback-cn

在收到您的详细细节信息后，我们将会进行快速处理。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by PshySimon** [comment]
把/res/raw/keep.xml拷贝到项目中去

**Comment by hugangyongxiangsha** [comment]
我也遇到一样的问题
